include:
  - project: 'ci-templates/gitlab-anybadge-creator'
    file: 'anybadges.yml'
  - project: 'ci-templates/composer-packages'
    file: 'composer-packages.yml'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - lint
  - test
  - packages
  - badges
  - release

"PHP CS Fixer":
  stage: test
  image: ekreative/php-cs-fixer:3
  script:
    - php-cs-fixer fix --dry-run --config=.Build/php-cs-fixer.php --diff
  only:
    changes:
      - "**/*.php"

"PHP Static Analyzer":
  stage: test
  image: composer:2
  before_script:
    - composer config --no-interaction allow-plugins.composer/installers true
    - composer config --no-interaction allow-plugins.typo3/class-alias-loader true
    - composer config --no-interaction allow-plugins.typo3/cms-composer-installers true
    - composer global require phpstan/phpstan
  script:
    - composer install --ignore-platform-reqs
    - /tmp/vendor/bin/phpstan analyse -l 4 -c .Build/phpstan.neon
  only:
    changes:
      - "**/*.php"

"PHP Rector Analyzer":
  stage: test
  image: composer:2
  before_script:
    - composer config --no-interaction allow-plugins.composer/installers true
    - composer config --no-interaction allow-plugins.typo3/class-alias-loader true
    - composer config --no-interaction allow-plugins.typo3/cms-composer-installers true
    - composer install --ignore-platform-reqs
    - mkdir build
    - apk update && apk add icu-dev
    - docker-php-ext-install intl
  script:
    - vendor/bin/rector process --config .Build/rector.php -n
  only:
    changes:
      - "**/*.php"

"Create Badge":
  stage: badges
  script:
    - latest_version=$(git describe --abbrev=0)
    - anybadge -l "Latest Version" -v $latest_version -f latestVersion.svg -c blue

.lint: &lint_tests
  stage: lint
  image: php:$PHP_VERSION
  script:
    - find . -not -path "./vendor/*" -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
  only:
    changes:
      - "**/*.php"

"Linting with PHP $PHP_VERSION":
  <<: *lint_tests
  parallel:
    matrix:
      - PHP_VERSION: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]

.unit_tests: &unit_tests
  stage: test
  image: php:$PHP_VERSION
  before_script:
    - apt-get update && apt-get install -y bash
    - bash ./.Build/docker_install.sh > /dev/null
    - composer config --no-interaction allow-plugins.composer/installers true
    - composer config --no-interaction allow-plugins.typo3/class-alias-loader true
    - composer config --no-interaction allow-plugins.typo3/cms-composer-installers true
    - composer install --ignore-platform-reqs
  script:
    - ls -l
    - XDEBUG_MODE=coverage vendor/bin/phpunit -c ./.Build/phpunit.xml
  artifacts:
    reports:
      junit: build/*-report.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  only:
    changes:
      - "**/*.php"

"Unit Tests with PHP $PHP_VERSION":
  <<: *unit_tests
  parallel:
    matrix:
      - PHP_VERSION: [ "8.1", "8.2", "8.3", "8.4"]

"Upload to TER":
  stage: release
  image: composer:2
  only:
    - tags
  before_script:
    - composer config --no-interaction allow-plugins.composer/installers true
    - composer config --no-interaction allow-plugins.typo3/class-alias-loader true
    - composer config --no-interaction allow-plugins.typo3/cms-composer-installers true
    - composer global require typo3/tailor
  script:
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$TYPO3_API_TOKEN" ] && [ -n "$TYPO3_EXTENSION_KEY" ]; then
        echo -e "Set version to ${CI_COMMIT_TAG} in ext_emconf.php"
        /tmp/vendor/bin/tailor set-version --no-docs -- $CI_COMMIT_TAG
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        /tmp/vendor/bin/tailor ter:publish --comment "$TAG_MESSAGE" "$CI_COMMIT_TAG" "$TYPO3_EXTENSION_KEY"
      fi;
